{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "722a0daf-8de5-46eb-bf26-174cbd509ef3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Starting Goldstone-Hyper-Holo-Fractal kernel test...\n",
      "Epoch 0: Loss 1.2852\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4903\n",
      "  Final state avg norm: 11.3137\n",
      "Epoch 10: Loss 1.3083\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4904\n",
      "  Final state avg norm: 11.3265\n",
      "Epoch 20: Loss 1.1779\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4885\n",
      "  Final state avg norm: 11.3373\n",
      "Epoch 30: Loss 1.1013\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4875\n",
      "  Final state avg norm: 11.3413\n",
      "Epoch 40: Loss 0.9827\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4864\n",
      "  Final state avg norm: 11.3527\n",
      "Epoch 50: Loss 0.9491\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4843\n",
      "  Final state avg norm: 11.3387\n",
      "Epoch 60: Loss 0.9414\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4821\n",
      "  Final state avg norm: 11.3202\n",
      "Epoch 70: Loss 0.9163\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4804\n",
      "  Final state avg norm: 11.3041\n",
      "Epoch 80: Loss 0.9420\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4798\n",
      "  Final state avg norm: 11.2981\n",
      "Epoch 90: Loss 0.9368\n",
      "  Trajectory coherence (std norm over 100 steps): 0.4788\n",
      "  Final state avg norm: 11.2877\n",
      "Kernel executed. Checking if bootstrapping valid...\n"
     ]
    }
   ],
   "source": [
    "# goldstone_hyper_holo_fractal_stable.py\n",
    "# Full prototype: Fractal + Hyper-Holographic + Goldstone modes kernel\n",
    "# Inspired by QCD SSB + Goldstone physics bones\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import numpy as np\n",
    "\n",
    "class GoldstoneHyperHoloBlock(nn.Module):\n",
    "    def __init__(self, dim=128, depth=5, alpha=1.7, slip_factor=0.15, ng_strength=0.05):\n",
    "        super().__init__()\n",
    "        self.depth = depth\n",
    "        self.alpha = alpha\n",
    "        self.proj = nn.Linear(dim, dim)\n",
    "        self.slip_gen = nn.Linear(dim, dim)\n",
    "        self.holo_proj = nn.Linear(dim * 2, dim * 4)\n",
    "        self.inv_holo = nn.Linear(dim * 4, dim)\n",
    "        self.ng_proj = nn.Linear(dim, dim)\n",
    "        self.ng_strength = ng_strength          # Increased from 0.02 to allow more fluctuation\n",
    "        self.slip_factor = slip_factor\n",
    "        self.norm_h = nn.LayerNorm(dim)         # Stabilize per-level\n",
    "        self.norm_out = nn.LayerNorm(dim)       # Final output stability\n",
    "\n",
    "    def forward(self, x, level=0, t_step=0.0, **kwargs):\n",
    "        if level >= self.depth:\n",
    "            return x\n",
    "\n",
    "        # Slip: symmetry breaking trigger\n",
    "        slip = torch.tanh(self.slip_gen(x)) * self.slip_factor\n",
    "        h = torch.relu(self.proj(x + slip))\n",
    "        h = self.norm_h(h)                      # Keep scale controlled\n",
    "\n",
    "        # Recursive child (fractal nesting)\n",
    "        h_child = self.forward(h, level + 1, t_step)\n",
    "\n",
    "        # Hyper-holographic projection\n",
    "        concat = torch.cat([h, h_child], dim=-1)\n",
    "        boundary = self.holo_proj(concat)\n",
    "        resolved = self.inv_holo(boundary)\n",
    "        fb = resolved * h\n",
    "\n",
    "        # SSB: vacuum expectation value with bounded noise\n",
    "        vev_rand = torch.tanh(torch.randn_like(h.mean(dim=-1, keepdim=True)))\n",
    "        vev = torch.norm(h, dim=-1, keepdim=True) * 0.005 * vev_rand\n",
    "        h_broken = h + vev\n",
    "\n",
    "        # Goldstone modes: soft fluctuations orthogonal to breaking\n",
    "        proj = self.ng_proj(h_broken)\n",
    "        norm_hb_sq = h_broken.norm(dim=-1, keepdim=True)**2 + 1e-6\n",
    "        dot = (proj * h_broken).sum(-1, keepdim=True) / norm_hb_sq\n",
    "        goldstone = proj - dot * h_broken\n",
    "        # No hard clamp — let norm handle outliers\n",
    "        phase = torch.sin(t_step * 2.0 * np.pi + torch.randn_like(goldstone) * 0.2)\n",
    "\n",
    "        # Add Goldstone fluctuation\n",
    "        h = h + self.ng_strength * goldstone * phase\n",
    "        h = self.norm_h(h)                      # Re-normalize after fluctuation\n",
    "\n",
    "        # Output + scale-free mask\n",
    "        out = x + fb + 0.05 * h_child\n",
    "        mask_prob = max(0.1, 1.0 / ((level + 1) ** self.alpha))  # Avoid total dropout\n",
    "        mask = (torch.rand_like(out) < mask_prob).float()\n",
    "        out = out * mask\n",
    "        out = self.norm_out(out)\n",
    "\n",
    "        return out\n",
    "\n",
    "\n",
    "class CoherenceNet(nn.Module):\n",
    "    def __init__(self, input_dim=64, hidden_dim=128):\n",
    "        super().__init__()\n",
    "        self.embed = nn.Linear(input_dim, hidden_dim)\n",
    "        self.fractal_core = GoldstoneHyperHoloBlock(hidden_dim)\n",
    "        self.head = nn.Linear(hidden_dim, input_dim)\n",
    "\n",
    "    def forward(self, x, steps=100):\n",
    "        h = self.embed(x)\n",
    "        states = [h.clone()]\n",
    "        for t in range(steps):\n",
    "            h = self.fractal_core(h, t_step=t / steps)\n",
    "            if torch.isnan(h).any() or torch.isinf(h).any():\n",
    "                print(f\"NaN/Inf detected in h at recursive step {t}\")\n",
    "                break\n",
    "            states.append(h.clone())\n",
    "        out = self.head(h)\n",
    "        return out, torch.stack(states)\n",
    "\n",
    "\n",
    "def test_run(steps=100, epochs=100):\n",
    "    model = CoherenceNet()\n",
    "    optimizer = optim.Adam(model.parameters(), lr=1e-3)  # Back to standard LR\n",
    "    criterion = nn.MSELoss()\n",
    "\n",
    "    x = torch.randn(32, 64)  # Batch 32, dim 64\n",
    "    for epoch in range(epochs):\n",
    "        out, states = model(x, steps=steps)\n",
    "        target = torch.roll(x, shifts=-1, dims=0)\n",
    "        loss = criterion(out, target)\n",
    "\n",
    "        if torch.isnan(loss).any() or torch.isinf(loss).any():\n",
    "            print(f\"NaN/Inf loss at epoch {epoch}\")\n",
    "            break\n",
    "\n",
    "        optimizer.zero_grad()\n",
    "        loss.backward()\n",
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # Gradient clipping\n",
    "        optimizer.step()\n",
    "\n",
    "        if epoch % 10 == 0:\n",
    "            coherence = states.norm(dim=-1).std()\n",
    "            final_norm = states[-1].norm(dim=-1).mean()\n",
    "            print(f\"Epoch {epoch}: Loss {loss.item():.4f}\")\n",
    "            print(f\"  Trajectory coherence (std norm over {steps} steps): {coherence.item():.4f}\")\n",
    "            print(f\"  Final state avg norm: {final_norm.item():.4f}\")\n",
    "\n",
    "    return model\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"Starting Goldstone-Hyper-Holo-Fractal kernel test...\")\n",
    "    model = test_run(steps=100, epochs=100)\n",
    "    print(\"Kernel executed. Checking if bootstrapping valid...\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f237b481-96e7-40f3-b57c-393f7a9752a7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
